<!DOCTYPE html>
<html>
<head>
    <title>Приклад форми на JavaScript</title>
    <script>
        function validateForm() {
            var x = document.forms["myForm"]["fname"].value;
            if (x == "") {
                alert("Please input this");
                return false;
            }
        }
    </script>
</head>
<body>
<h2>Reg</h2>
<form name="myForm" onsubmit="return validateForm()" method="post">
    <label for="fname">NAme:</label>
    <input type="text" id="fname" name="fname"><br><br>
    <label for="lname">Second name:</label>
    <input type="text" id="lname" name="lname"><br><br>
    <input type="submit" value="Send">
</form>
</body>
</html>