<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<div class="form-row">
    <div class="form-group col-md-6">
        <form method="post" action="/add" class="form-inline">
            <input type="text" name="name" class="form-control" placeholder="tree name">
            <input type="number" name="age" class="form-control" placeholder="age of tree">

            <button type="submit" class="btn btn-primary ml-2">Add new tree</button>
        </form>
    </div>
</div>

</body>
</html>